name: PythonTest

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  check:
    name: Check files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: check modified files
        id: check_files
        run: |
          echo "=============== list modified files ==============="
          git diff --name-only HEAD^ HEAD

          echo "========== check paths of modified files =========="
          git diff --name-only HEAD^ HEAD > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file != lab2/* ]]; then
              echo "This modified file is not under the 'lab1' folder."
              echo "::set-output name=run_job::false"
              break
            else
              echo "::set-output name=run_job::true"
            fi
          done < files.txt

  test:
    needs: check
    if: needs.check.outputs.run_job == 'true'

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: run tests
        working-directory: ${{github.workspace}}/lab2/
        shell: bash
        run: |
          pwd
          ls
          echo "Testing lab2 ..."
          echo "unit tests ..."
          python3 unit_tests.py
          echo "stress tests ..."
          python3 stress_tests.py
          echo "done!"

      - name: run profiling
        working-directory: ${{github.workspace}}/lab2/
        shell: bash
        run: |
          echo "start profiling"
